apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shadowflight-backend
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app: shadowflight-backend
      chart: {{ template "shadowflight-backend.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      version: {{ .Values.image.tag }}