apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shadowflight-backend-vs
  labels:
    app: shadowflight-backend
    chart: {{ template "shadowflight-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag }}
    annotations:
      argocd.argoproj.io/sync-wave: "-4"
spec:
  hosts:
    - "{{ .Values.primaryDomainName }}"
  gateways:
    - istio-system/shadowflight-gateway
  http:
    - name: shadowflight-backend-http
      route:
        - destination:
            host: shadowflight-backend.shadowflight.svc.cluster.local
            port:
              number: 8080
