apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  replicas: {{ int .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }} # Default to 10 if not specified
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        chart: {{ template "shadowflight-backend.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        version: {{ .Values.image.tag }}
        tags.datadoghq.com/env: {{ .Values.datadog.env }}
        tags.datadoghq.com/service: {{ .Values.applicationName }}
        tags.datadoghq.com/version: {{ .Values.image.tag }}
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.19.0
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        {{- if ne .Values.disableVault true }}
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: "{{ .Values.vault.role }}"
        vault.hashicorp.com/agent-inject-secret-secrets: "{{ .Values.vault.path }}"
        {{- toYaml .Values.vault.secretFormat | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      imagePullSecrets:
        - name: {{ .Values.image.imageSecretName}}
      containers:
        - name: {{ .Values.applicationName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              name: http
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
            {{- if ne .Values.disableVault true }}
            - name: BASH_ENV
              value: /vault/secrets/secrets
            {{- end }}
            - name: DEBUG
              value: "true"
          {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
      nodeSelector:
          node.group: {{ .Values.nodegroup }}
      restartPolicy: Always
      {{- if .Values.volumes }}
      volumes:
      {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
