{{- if eq .Values.service.template "default" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  selector:
    app: {{ .Values.applicationName }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
{{- end }}
