apiVersion: v1
kind: Service
metadata:
  name: shadowflight-backend
  labels:
    app: shadowflight-backend
spec:
  selector:
    app: shadowflight-backend
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
