apiVersion: v1
kind: Service
metadata:
  name: shadowflight-backend
  labels:
    app: shadowflight-backend
    chart: {{ template "shadowflight-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag }}
spec:
  selector:
    app: shadowflight-backend
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
