{{- if .Values.service.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.applicationName }}-vs
  labels:
    app: {{ .Values.applicationName }}
spec:
  hosts:
    - "{{ .Values.primaryDomainName }}"
    {{- if .Values.secondaryDomainName }}
    - "{{ .Values.secondaryDomainName }}"
    {{- end }}
  gateways:
    - {{ .Values.service.istioGateway }}
  http:
    - name: {{ .Values.applicationName }}-http
      route:
        - destination:
            host: {{ .Values.service.vsDestination }}
            port:
              number: {{ .Values.service.containerPort }}
{{ end }}
