# Default values for shadowflight-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  template: "default"
job:
  template: ""
  schedule: ""
  suspend: "false"

applicationName: significo-app
nameOverride: ""
fullnameOverride: ""
serviceAccountName: shadowflight
replicaCount: 1
revisionHistoryLimit: 0
nodegroup: dev
image:
  repository: significo/significo-app
  tag: latest
  pullPolicy: Always
  imageSecretName: significo-dockerhub
vault:
  path: kv/data/shadowflight/dev/
  role: shadowflight
  secretFormat:
    vault.hashicorp.com/agent-inject-template-secrets: |
        {{`{{- with secret "`}}{{ .Values.vault.path }}" -}}
             {{` set -e
              {{- range $key, $value := .Data.data }}
                export {{ $key }}={{ $value }}
              {{- end }}
            {{- end }}`}}

primaryDomainName: recco-api.significo.dev
resources:
  requests:
    cpu: "1"
    memory: "2Gi"
service:
  template: "default"
  type: ClusterIP
  containerPort: 8080
  vsDestination: shadowflight-backend.shadowflight.svc.cluster.local
  istioGateway: istio-system/shadowflight-gateway
  virtualService:
    enabled: false
springProfilesActive: prod
datadog:
  env: dev
