name: Helm Chart Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: 'v3.7.1' # Update to the desired Helm version

    - name: Lint Helm Chart
      run: |
        NEW_VERSION=${{ github.event.release.tag_name }}
        sed -i "s/^version: .*/version: $NEW_VERSION/" significo-chart/Chart.yaml
        helm lint significo-chart

    - name: Package Helm Chart
      run: |
        NEW_VERSION=${{ github.event.release.tag_name }}
        sed -i "s/^version: .*/version: $NEW_VERSION/" significo-chart/Chart.yaml
        helm package ./significo-chart
  
    - name: Publish
      run: |
        echo ${{ secrets.SIAB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        helm push significo-chart-${{ github.event.release.tag_name }} ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.sha }}


    - name: Clean up
      run: rm -f ./significo-chart-2023.7.1.tgz

